analyzer:
  errors:
    file_names: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    unused_import: ignore
    use_key_in_widget_constructors: ignore
    use_super_parameters: ignore
include: package:flutter_lints/flutter.yaml
